# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow=MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(180, 160)
        self.MainWindow.setMinimumSize(QtCore.QSize(180, 160))
        self.MainWindow.setMaximumSize(QtCore.QSize(180, 160))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 160, 112))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.dropAllHP = QtWidgets.QPushButton(self.formLayoutWidget)
        self.dropAllHP.setObjectName("dropAllHP")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dropAllHP)
        self.dropAllBank = QtWidgets.QPushButton(self.formLayoutWidget)
        self.dropAllBank.setObjectName("dropAllBank")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dropAllBank)
        self.burn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.burn.setObjectName("burn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.burn)
        self.poison = QtWidgets.QPushButton(self.formLayoutWidget)
        self.poison.setObjectName("poison")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.poison)
        self.paralyze = QtWidgets.QPushButton(self.formLayoutWidget)
        self.paralyze.setObjectName("paralyze")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.paralyze)
        self.sleep = QtWidgets.QPushButton(self.formLayoutWidget)
        self.sleep.setObjectName("sleep")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sleep)
        self.DropHalfPP = QtWidgets.QPushButton(self.formLayoutWidget)
        self.DropHalfPP.setObjectName("DropHalfPP")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.DropHalfPP)
        self.HealEnemy = QtWidgets.QPushButton(self.formLayoutWidget)
        self.HealEnemy.setObjectName("HealEnemy")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HealEnemy)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 180, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dropAllHP.setText(_translate("MainWindow", "All HP drop"))
        self.dropAllBank.setText(_translate("MainWindow", "All Bank Drop"))
        self.burn.setText(_translate("MainWindow", "Burn"))
        self.poison.setText(_translate("MainWindow", "Posion"))
        self.paralyze.setText(_translate("MainWindow", "Paralyze"))
        self.sleep.setText(_translate("MainWindow", "Sleep"))
        self.DropHalfPP.setText(_translate("MainWindow", "Half PP drop"))
        self.HealEnemy.setText(_translate("MainWindow", "Heal enemy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
